[build]
command = """
python -m pip install --upgrade pip
pip install -r requirements.txt
"""
publish = "."

[build.environment]
PYTHON_VERSION = "3.11.0"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
